<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitd3732690a82edcd544184940db831175
{
    public static $prefixLengthsPsr4 = array (
        'D' => 
        array (
            'Dotenv\\' => 7,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Dotenv\\' => 
        array (
            0 => __DIR__ . '/..' . '/vlucas/phpdotenv/src',
        ),
    );

    public static $prefixesPsr0 = array (
        'Z' => 
        array (
            'Zend\\Validator\\' => 
            array (
                0 => __DIR__ . '/..' . '/zendframework/zend-validator',
            ),
            'Zend\\Stdlib\\' => 
            array (
                0 => __DIR__ . '/..' . '/zendframework/zend-stdlib',
            ),
            'Zend\\ServiceManager\\' => 
            array (
                0 => __DIR__ . '/..' . '/zendframework/zend-servicemanager',
            ),
            'Zend\\Mime\\' => 
            array (
                0 => __DIR__ . '/..' . '/zendframework/zend-mime',
            ),
            'Zend\\Math\\' => 
            array (
                0 => __DIR__ . '/..' . '/zendframework/zend-math',
            ),
            'Zend\\Mail\\' => 
            array (
                0 => __DIR__ . '/..' . '/zendframework/zend-mail',
            ),
            'Zend\\Loader\\' => 
            array (
                0 => __DIR__ . '/..' . '/zendframework/zend-loader',
            ),
            'Zend\\Crypt\\' => 
            array (
                0 => __DIR__ . '/..' . '/zendframework/zend-crypt',
            ),
        ),
        'M' => 
        array (
            'Mustache' => 
            array (
                0 => __DIR__ . '/..' . '/mustache/mustache/src',
            ),
        ),
    );

    public static $fallbackDirsPsr0 = array (
        0 => __DIR__ . '/../../..' . '/www/class',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitd3732690a82edcd544184940db831175::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitd3732690a82edcd544184940db831175::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInitd3732690a82edcd544184940db831175::$prefixesPsr0;
            $loader->fallbackDirsPsr0 = ComposerStaticInitd3732690a82edcd544184940db831175::$fallbackDirsPsr0;

        }, null, ClassLoader::class);
    }
}
